[package]

name = "shapefile"
description = "Rust read/write support for shapefiles"
license = "Apache-2.0"
version = "0.0.1"
authors = [
    "Corey Farwell <coreyf@rwell.org>",
    "Ben Evans <ben@bluechimp.io>"
]

[dependencies]
nom = "3.0"
